#!/usr/bin/env bash

set -eux

KUBERNETES_SLES_VERSION="${KUBERNETES_VERSION//v}"
CRIO_SLES_VERSION="${CRIO_VERSION//v}"
CRICTL_SLES_VERSION="${CRICTL_VERSION//v}"

sudo cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
overlay
br_netfilter
EOF

# Set up required sysctl params, these persist across reboots.
sudo cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sudo zypper -n in --repo kubernetes kubelet="${KUBERNETES_SLES_VERSION}" kubeadm="${KUBERNETES_SLES_VERSION}" kubectl="${KUBERNETES_SLES_VERSION}"
sudo zypper -n in --repo CRI-O cri-o="${CRIO_SLES_VERSION}" cri-tools="${CRICTL_SLES_VERSION}"
# keepalived is in the external oss repo, hence install it here.
sudo zypper -n in keepalived
# Install NM and enable it.
sudo zypper -n in NetworkManager
