presubmits:
  Nordix/metal3-dev-tools:
  - name: shellcheck
    run_if_changed: '((\.sh)|^Makefile)$'
    branches:
    - main
    decorate: true
    spec:
      containers:
      - args:
        - ./scripts/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/koalaman/shellcheck-alpine:v0.10.0@sha256:5921d946dac740cbeec2fb1c898747b6105e585130cc7f0602eec9a10f7ddb63
        imagePullPolicy: Always
  - name: markdownlint
    run_if_changed: '(\.md|markdownlint\.sh)$'
    branches:
    - main
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/pipelinecomponents/markdownlint-cli2:0.14.19@sha256:c651559a31fefc82cf864486d9472338ffa0aaa529ebf71a035d4f1d913809aa
        imagePullPolicy: Always
