#!/usr/bin/env bash

set -eux

export KUBERNETES_MINOR_VERSION=${KUBERNETES_VERSION%.*}
export CRIO_MINOR_VERSION=${CRIO_VERSION%.*}

sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config

cat <<EOF | tee /etc/yum.repos.d/cri-o.repo
[cri-o]
name=CRI-O
baseurl=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/${CRIO_MINOR_VERSION}/rpm/
enabled=1
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/${CRIO_MINOR_VERSION}/rpm/repodata/repomd.xml.key
EOF

sudo yum -y update
