apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- traefik
- staging-cluster-issuer-http.yaml
- cluster-issuer-http.yaml
- certificate.yaml
- storageclass.yaml
- referencegrant.yaml
