presubmits:
  metal3-io/metal3-io.github.io:
  - name: shellcheck
    run_if_changed: '((\.sh)|^Makefile)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/koalaman/shellcheck-alpine:v0.11.0@sha256:9955be09ea7f0dbf7ae942ac1f2094355bb30d96fffba0ec09f5432207544002
        imagePullPolicy: Always
  - name: markdownlint
    run_if_changed: '(\.md|markdownlint\.sh)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/pipelinecomponents/markdownlint-cli2:0.14.19@sha256:c651559a31fefc82cf864486d9472338ffa0aaa529ebf71a035d4f1d913809aa
        imagePullPolicy: Always
  - name: spellcheck
    run_if_changed: '(\.md|spellcheck\.sh|.cspell-config.json)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/spellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: ghcr.io/streetsidesoftware/cspell:8.13.3@sha256:03df0e485775a43531c9c0e829227f39b3380796e92faab4166137dc5712d40a
        imagePullPolicy: Always
