#!/usr/bin/env bash

set -eux

sudo dnf distro-sync -y

# Install EPEL repo (later required by atop, python3-bcrypt and python3-passlib)
sudo dnf install epel-release -y

# Install podman
sudo dnf install podman -y

# Without this minikube cannot start properly kvm and fails.
# As a simple workaround, this will create an empty file which can
# disable the new firmware, more details here [1], look for firmware description.
# [1] <https://libvirt.org/formatdomain.html#operating-system-booting>
# upstream commit fixing the behavior to not print error messages for unknown features
# will be included in RHEL-AV-8.5.0 by next rebase to libvirt 7.4.0.
sudo mkdir -p /etc/qemu/firmware
sudo touch /etc/qemu/firmware/50-edk2-ovmf-cc.json
