apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: url
    remoteRef:
      # <item-name>/[section-name/]<file-name>
      key: "alertmanager-slack-webhook/url"
