apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.8.5
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
