apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: openstack
  namespace: capo-system
spec:
  version: v0.11.1
---
apiVersion: v1
kind: Namespace
metadata:
  name: capo-system
