{
 "title": "plank dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(prowjobs{job=~\"plank|prow-controller-manager\"}, cluster)"
   },
   {
    "name": "org",
    "label": "org",
    "query": "label_values(prowjobs{job=~\"plank|prow-controller-manager\"}, org)"
   },
   {
    "name": "repo",
    "label": "repo",
    "query": "label_values(prowjobs{job=~\"plank|prow-controller-manager\"}, repo)"
   },
   {
    "name": "state",
    "label": "state",
    "query": "all,aborted,error,failure,pending,success,triggered"
   },
   {
    "name": "type",
    "label": "type",
    "query": "all,batch,periodic,presubmit,postsubmit"
   },
   { "name": "group_by_1", "label": "group_by_1", "query": "cluster,org,repo,state,type" },
   { "name": "group_by_2", "label": "group_by_2", "query": "cluster,org,repo,state,type" },
   { "name": "group_by_3", "label": "group_by_3", "query": "cluster,org,repo,state,type" }
  ]
 },
 "panels": [
  {
   "title": "number of Prow jobs (stacked) by ${group_by_1}",
   "type": "graph",
   "description": "sum(prowjobs{...}) by (${group_by_1})",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=~\"plank|prow-controller-manager\",cluster=~\"${cluster}\",org=~\"${org}\",repo=~\"${repo}\",state=~\"${state}\",type=~\"${type}\"}) by (${group_by_1})",
     "legendFormat": "{{${group_by_1}}}"
    }
   ]
  },
  {
   "title": "number of Prow jobs (stacked) by ${group_by_2}",
   "type": "graph",
   "description": "sum(prowjobs{...}) by (${group_by_2})",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=~\"plank|prow-controller-manager\",cluster=~\"${cluster}\",org=~\"${org}\",repo=~\"${repo}\",state=~\"${state}\",type=~\"${type}\"}) by (${group_by_2})",
     "legendFormat": "{{${group_by_2}}}"
    }
   ]
  },
  {
   "title": "number of Prow jobs (stacked) by ${group_by_3}",
   "type": "graph",
   "description": "sum(prowjobs{...}) by (${group_by_3})",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=~\"plank|prow-controller-manager\",cluster=~\"${cluster}\",org=~\"${org}\",repo=~\"${repo}\",state=~\"${state}\",type=~\"${type}\"}) by (${group_by_3})",
     "legendFormat": "{{${group_by_3}}}"
    }
   ]
  }
 ]
}