#!/usr/bin/env bash

set -eux

export KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.29"}
export CRICTL_VERSION=${CRICTL_VERSION:-"v1.29"}
export CRIO_VERSION=${CRIO_VERSION:-"v1.29"}

sudo cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
overlay
br_netfilter
EOF

# Set up required sysctl params, these persist across reboots.
sudo cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

sudo sysctl --system

sudo yum install -y kubelet kubeadm kubectl cri-o cri-tools
sudo apt-mark hold kubelet kubeadm kubectl cri-o cri-tools

sudo systemctl enable --now crio
sudo systemctl enable --now kubelet

for container in $(env | grep "CALICO_*" | cut -f2 -d'='); do
  sudo crictl pull "${container}"
done

sudo sed -i "0,/.*PermitRootLogin.*/s//PermitRootLogin yes/" /etc/ssh/sshd_config
