#!/usr/bin/env bash

set -eux

export KUBERNETES_MINOR_VERSION=${KUBERNETES_VERSION%.*}
export KUBERNETES_BINARIES_VERSION="${KUBERNETES_BINARIES_VERSION:-${KUBERNETES_VERSION}}"
export CRIO_BINARIES_VERSION="${CRIO_BINARIES_VERSION:-${CRIO_VERSION}}"
export CRICTL_BINARIES_VERSION="${CRICTL_BINARIES_VERSION:-${CRICTL_VERSION}}"

sudo cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
overlay
br_netfilter
EOF

# Set up required sysctl params, these persist across reboots.
sudo cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sudo yum install -y container-selinux

if [[ "${PRE_RELEASE:-}" == "true" ]]; then
  # See https://github.com/containernetworking/plugins/releases
  CNI_PLUGINS_VERSION="v1.7.1"

  # Kubernetes release tooling
  # See https://github.com/kubernetes/release/releases
  RELEASE_VERSION="${RELEASE_VERSION:-v0.18.0}"

  case $(uname -m) in
    x86_64) ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
    *) echo "Unsupported architecture: $(uname -m)"; exit 1 ;;
  esac

  DEST="/opt/cni/bin"
  sudo mkdir -p "${DEST}"
  curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGINS_VERSION}/cni-plugins-linux-${ARCH}-${CNI_PLUGINS_VERSION}.tgz" | sudo tar -C "${DEST}" -xz
  curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${ARCH}.tar.gz" | sudo tar -C /usr/local/bin -xz

  sudo curl -L --remote-name-all https://dl.k8s.io/release/${KUBERNETES_VERSION}/bin/linux/${ARCH}/{kubeadm,kubelet}
  curl -LO "https://dl.k8s.io/release/${KUBERNETES_VERSION}/bin/linux/${ARCH}/kubectl"

  sudo install kubeadm kubelet /usr/bin/
  sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

  curl -L --output 10-kubeadm.conf "https://github.com/kubernetes/release/raw/${RELEASE_VERSION}/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf"
  sudo mkdir -p /usr/lib/systemd/system/kubelet.service.d
  sudo mv 10-kubeadm.conf /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
  curl -L --output kubelet.service "https://github.com/kubernetes/release/raw/${RELEASE_VERSION}/cmd/krel/templates/latest/kubelet/kubelet.service"
  sudo mv kubelet.service /usr/lib/systemd/system/kubelet.service
else
  sudo yum install -y kubelet-"${KUBERNETES_BINARIES_VERSION//v}" kubeadm-"${KUBERNETES_BINARIES_VERSION//v}" kubectl-"${KUBERNETES_BINARIES_VERSION//v}" cri-tools-"${CRICTL_BINARIES_VERSION//v}"
fi

sudo yum install -y cri-o-"${CRIO_BINARIES_VERSION//v}"

sudo pip install kubernetes
