#!/usr/bin/env bash

# Prepull container images that are later used in CI tests
set -uex

export CONTAINER_RUNTIME=${CONTAINER_RUNTIME:-"podman"}
# Container images that we pre-pull into the CI image.
export IMG_REGISTRY="${IMG_REGISTRY:-"docker.io/registry:latest"}"
export IMG_GOLANG_IMG="${IMG_GOLANG_IMG:-"docker.io/golang:1.21"}"
export IMG_CENTOS_IMG="${IMG_CENTOS_IMG:-"quay.io/centos/centos:stream9"}"
export IMG_UBUNTU_IMG="${IMG_UBUNTU_IMG:-"docker.io/ubuntu:22.04"}"

for container in $(env | grep "IMG_*" | cut -f2 -d'='); do
  sudo "${CONTAINER_RUNTIME}" pull "${container}"
done
