#!/usr/bin/env bash

set -eux

sudo sed -i "0,/.*PermitRootLogin.*/s//PermitRootLogin yes/" /etc/ssh/sshd_config

sudo cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
overlay
br_netfilter
EOF

# Set up required sysctl params, these persist across reboots.
sudo cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

KUBERNETES_DEB_VERSION="${KUBERNETES_VERSION//v}"-\*
CRIO_DEB_VERSION="${CRIO_VERSION//v}"-\*
CRICTL_DEB_VERSION="${CRICTL_VERSION//v}"-\*

sudo apt-get install -y kubelet="${KUBERNETES_DEB_VERSION}" kubeadm="${KUBERNETES_DEB_VERSION}" kubectl="${KUBERNETES_DEB_VERSION}" cri-o="${CRIO_DEB_VERSION}" cri-tools="${CRICTL_DEB_VERSION}"
sudo apt-mark hold kubelet kubeadm kubectl cri-o cri-tools
