#!/usr/bin/env bash

set -eux

## Install atop and sysstat
sudo zypper refresh
sudo zypper -n in atop sysstat

# Switch from wicked to NetworkManager.
sudo zypper -n in NetworkManager
sudo systemctl disable wicked wickedd
sudo systemctl enable NetworkManager

# Add metal3ci user to libvirt group
sudo usermod -aG libvirt metal3ci
