#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

MODULES=${ADDITIONAL_IPA_KERNEL_MODULES:-""}

for mod_name in $MODULES; do
    echo "$mod_name" >> /etc/modules-load.d/load.conf
done

