apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-dispatch-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      # <item-name>/[section-name/]<field-name>
      key: "flux-github-dispatch-token/password"
