---
- hosts: localhost
  environment:
    NUM_NODES:  "{{ lookup('env', 'NUM_NODES') }}"
    CONTROL_PLANE_MACHINE_COUNT: "{{ lookup('env', 'CONTROL_PLANE_MACHINE_COUNT') }}"
    WORKER_MACHINE_COUNT: "{{ lookup('env', 'WORKER_MACHINE_COUNT') }}"
  vars_files:
    - default_vars/vars.yaml
  tasks:
  - name: Cleanup Bare Metal Lab
    include_tasks: tasks/cleanup-tasks.yaml
