---
- hosts: localhost
  environment:
    NUM_NODES:  "{{ lookup('env', 'NUM_NODES') }}"
    CONTROL_PLANE_MACHINE_COUNT: "{{ lookup('env', 'CONTROL_PLANE_MACHINE_COUNT') }}"
    WORKER_MACHINE_COUNT: "{{ lookup('env', 'WORKER_MACHINE_COUNT') }}"
    DHCP_HOSTS: "{{ DHCP_HOSTS }}"
    DHCP_IGNORE: "{{ DHCP_IGNORE }}"
  vars_files:
    - default_vars/vars.yaml
  tasks:
  - name: Deploy Bare Metal Lab
    block:
      - include_tasks: tasks/cleanup-tasks.yaml
      - include_tasks: tasks/deploy-tasks.yaml
