apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloud-config
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: cloud.conf
    remoteRef:
      # <item-name>/[section-name/]<file-name>
      key: "xerces-credentials/cloud.conf"
